/**********************************************************************************************************************
 *  FILE DESCRIPTION
 *  -----------------------------------------------------------------------------------------------------------------*/
/**        \file  INTCTRL_Lcfg.c
 *        \brief  The source file for the linking configurations for interrupt control Driver
 *
 *      \details  NULL
 *
 *
 *********************************************************************************************************************/

/**********************************************************************************************************************
 *  INCLUDES
 *********************************************************************************************************************/
#include "INTCTRL_Cfg.h"
const STR_InterruptCfg_t aSTR_InterruptCfg[INTERRUPTS_NUMBER] = 
{
    /**-System Interrupts-**/
    {MemoryManagement_IRQn, INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {BusFault_IRQn,         INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {UsageFault_IRQn,       INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {SVCall_IRQn,           INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {DebugMonitor_IRQn,     INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {PendSV_IRQn,           INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {SysTick_IRQn,          INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    /**-peripheral Interrupts-**/
    {GPIOA_IRQn,            INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {GPIOB_IRQn,            INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_7}},
    {GPIOA_IRQn,            INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {GPIOB_IRQn,            INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {GPIOC_IRQn,            INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {GPIOD_IRQn,            INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {GPIOE_IRQn,            INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {UART0_IRQn,            INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {UART1_IRQn,            INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {SSI0_IRQn,             INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {I2C0_IRQn,             INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {PWM0_FAULT_IRQn,       INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {PWM0_0_IRQn,           INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {PWM0_1_IRQn,           INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {PWM0_2_IRQn,           INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {QEI0_IRQn,             INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {ADC0SS0_IRQn,          INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {ADC0SS1_IRQn,          INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {ADC0SS2_IRQn,          INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {ADC0SS3_IRQn,          INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {WATCHDOG0_IRQn,        INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {TIMER0A_IRQn,          INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {TIMER0B_IRQn,          INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {TIMER1A_IRQn,          INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {TIMER1B_IRQn,          INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {TIMER2A_IRQn,          INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {TIMER2B_IRQn,          INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {COMP0_IRQn,            INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {COMP1_IRQn,            INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {SYSCTL_IRQn,           INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {FLASH_CTRL_IRQn,       INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {GPIOF_IRQn,            INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {UART2_IRQn,            INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {SSI1_IRQn,             INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {TIMER3A_IRQn,          INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {TIMER3B_IRQn,          INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {I2C1_IRQn,             INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {QEI1_IRQn,             INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {CAN0_IRQn,             INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {CAN1_IRQn,             INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {HIB_IRQn,              INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {USB0_IRQn,             INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {PWM0_3_IRQn,           INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {UDMA_IRQn,             INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {UDMAERR_IRQn,          INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {ADC1SS0_IRQn,          INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {ADC1SS1_IRQn,          INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {ADC1SS2_IRQn,          INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {ADC1SS3_IRQn,          INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {SSI2_IRQn,             INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {SSI3_IRQn,             INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {UART3_IRQn,            INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {UART4_IRQn,            INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {UART5_IRQn,            INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {UART6_IRQn,            INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {UART7_IRQn,            INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {I2C2_IRQn,             INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {I2C3_IRQn,             INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {TIMER4A_IRQn,          INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {TIMER4B_IRQn,          INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {TIMER5A_IRQn,          INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {TIMER5B_IRQn,          INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {WTIMER0A_IRQn,         INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {WTIMER0B_IRQn,         INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {WTIMER1A_IRQn,         INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {WTIMER1B_IRQn,         INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {WTIMER2A_IRQn,         INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {WTIMER2B_IRQn,         INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {WTIMER3A_IRQn,         INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {WTIMER3B_IRQn,         INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {WTIMER4A_IRQn,         INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {WTIMER4B_IRQn,         INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {WTIMER5A_IRQn,         INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {WTIMER5B_IRQn,         INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {SYSEXC_IRQn,           INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {PWM1_0_IRQn,           INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {PWM1_1_IRQn,           INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {PWM1_2_IRQn,           INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {PWM1_3_IRQn,           INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}},
    {PWM1_FAULT_IRQn,       INTERRUPT_ENABLED, {GROUP_YYY_PRIORITY_0,SUBGROUP_YYY_PRIORITY_1}}
};
